const products = [
  {
    _id: '1',
    name: 'Black and White Cake',
    image: '/images/bw-cake.jpg',
    description:'Moist vanilla cake with chocolate, mocha, and vanilla buttercream frosting.',
    category: 'Cake',
    price: 49.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Fruit Tartlets',
    image: '/images/fruit-tart.jpg',
    description:'1 dozen bite-sized fruit tarts with assorted fruit toppings. Buttery base, creamy vanilla filling and sweet fruit topping',
    category: 'Pastry',
    price: 59.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Strawberry Cupcakes',
    image: '/images/straw-cupcake.jpg',
    description: '1 dozen buttery vanilla cupcakes topped with strawberry buttercream and a strawberry topper.',
    category: 'Cupcake',
    price: 39.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Macaron Cake',
    image: '/images/macaron-cake.jpg',
    description:
      'A stunning cake for special occasions. 4 layer cake with buttercream frosting and handmade macarons.',
    category: 'Cake',
    price: 79.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Donuts',
    image: '/images/donuts.jpg',
    description: '6 fresh fun donuts with assorted toppings.',
    category: 'Pastry',
    price: 29.99,
    countInStock: 7,
    rating: 4.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Chocolate Layer Cake',
    image: '/images/choc-layer.jpg',
    description:
      'A creamy delicious cake with chocolate base, white chocolate and dark chocolate mousse layers, topped with chocolate ganache.',
    category: 'Cake',
    price: 69.99,
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
]

export default products
